### ISSUE TITLE
callback option doesn't work 

### ISSUE THREAD

**Issue by all4miller** [afeld/jeditable-rails#6] opened 2011-02-21 22:09 UTC
Hi

The callback jeditable option doesn't work. Looks like it's due to the fact the function passed is a string from resulting args.to_json.

Cheers

**Comment by afeld** [comment] 2011-02-23 04:15
(duplicate of [issue #7](https://github.com/afeld/jeditable-rails/issues#issue/7))

**Closed as completed by afeld** 2011-02-23 04:15 UTC
Labels: Bug
